services:
  - type: web
    name: text-leech-bot
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/AshutoshGoswami24/text-leech-bot-for-render
    branch: main
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PORT
        value: 8000
